### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by mbrookes** [ixdi/material-design-iconic-font#6]
ixdi:material-design-iconic-font was upgraded from 2.1.2 to 2.1.3 as part of the upgrade to Meteor 1.2, but now I get an error in Chrome 45:

```
Failed to decode downloaded font: http://localhost:3000/packages/ixdi_material-design-iconic-font/material-design-iconic-font/dist/fonts/Material-Design-Iconic-Font.woff2?v=2.1.0
modernizr.custom.js:190OTS parsing error: invalid version tag
```

It was fine before the upgrade. Any ideas? Thanks.

**Comment by ixdi** [comment]
Try it now, thanks

**Comment by mbrookes** [comment]
That did the trick, thanks!

**Comment by TimFletcher** [comment]
I'm still getting this issue. I've uninstalled and reinstalled to no avail.

I'm running `ixdi:material-design-iconic-font@2.1.4` on the latest Meteor `METEOR@1.2.0.1` on OS X.

```
Failed to decode downloaded font: http://localhost:3000/packages/ixdi_material-design-iconic-font/Material-Design-Iconic-Font.woff?v=2.1.0
campaigns:1 OTS parsing error: invalid version tag
campaigns:1 Failed to decode downloaded font: http://localhost:3000/packages/ixdi_material-design-iconic-font/Material-Design-Iconic-Font.ttf?v=2.1.0
campaigns:1 OTS parsing error: invalid version tag
```

**Comment by mbrookes** [comment]
Yes, sorry - it's either back, or (more likely) I was mistaken and it never went away. (That said, I was sure previously the icons didn't display correctly, where they do now...)

**Comment by ixdi** [comment]
Upgrade. I think it's ok now, there's no alert in my computer.

**Comment by mbrookes** [comment]
Looks good from here, thanks @ixdi. (Safari, Firefox & Chrome latest on OS X 10.9.5)

**Comment by 3210jr** [comment]
Hi,
I just started a new project and this issue seems to be back. Any chance you can take a look at it?

Thanks
